/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tsubaki-red':              '#ae2826',
        'primary':                  '#8c0b12',
        'on-primary':               '#ffffff',
        'sumire-purple':            '#712ae2',
        'secondary':                '#712ae2',
        'secondary-container':      '#8b4bfc',
        'charcoal-text':            '#1f2937',
        'on-surface':               '#121c2a',
        'on-surface-variant':       '#59413e',
        'on-background':            '#121c2a',
        'surface':                  '#f8f9ff',
        'surface-stone':            '#f7f7f5',
        'surface-lowest':           '#ffffff',
        'surface-low':              '#f0f0ee',
        'surface-card':             '#ffffff',
        'surface-bright':           '#f8f9ff',
        'surface-container':        '#e6eeff',
        'surface-container-low':    '#eff3ff',
        'surface-container-high':   '#dfe9fc',
        'surface-container-highest':'#d9e3f7',
        'surface-container-lowest': '#ffffff',
        'surface-variant':          '#d9e3f7',
        'surface-dim':              '#d0daee',
        'outline':                  '#8d706d',
        'outline-variant':          '#e1bfbb',
        'error':                    '#ba1a1a',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',
        'error-bg':                 '#ffdad6',
        'on-muted':                 '#59413e',
        'charcoal':                 '#121c2a',
        'inverse-surface':          '#273140',
        'inverse-on-surface':       '#ebf1ff',
      },
      fontFamily: {
        display:      ['"Plus Jakarta Sans"', 'sans-serif'],
        'h2':         ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg':['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md':['"Plus Jakarta Sans"', 'sans-serif'],
        body:         ['Inter', 'sans-serif'],
        'body-md':    ['Inter', 'sans-serif'],
        'body-lg':    ['Inter', 'sans-serif'],
        'label-md':   ['Inter', 'sans-serif'],
        'caption':    ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display':        ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg':    ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md':    ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'h1':             ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'h2':             ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg':        ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':        ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md':       ['14px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '500' }],
        'caption':        ['12px', { lineHeight: '1.2', fontWeight: '400' }],
      },
      spacing: {
        'xs':     '4px',
        'sm':     '12px',
        'base':   '8px',
        'md':     '24px',
        'lg':     '48px',
        'xl':     '80px',
        'gutter': '24px',
        'max-width-desktop': '1200px',
      },
      maxWidth: {
        'max-width-desktop': '1200px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1.5rem',
        '3xl':   '1.75rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};
